name: geo_direction
description: A package to find routes between geolocation points.
version: 0.0.1
homepage: https://github.com/viniciusoliverrs/flutter_geo_router

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  http: ^0.13.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: